sudo: false
dist: xenial

language: python

env:
  global:
    secure: "YFZlAlyP9Z2AHcUJPnMonu3Jw7vnqCCmDoTzv4Bwcc/MTchBmEG6AREJGic+mVjEYfSvYmoKcAjmujfrbzETzYsEKVBxPqJjvWkj/bK+A0sucdDoJ/R3fm1mzh7QkzqMGLaEUd4I1b3jkqwfL3Ct88w+47jm/ampOOBTgcJlH0whOAtlb2AG3IPFJADixgSC56PHwVzEMOVfmfjwcLkU07Tx0a3trSGmOXQhzCY9ciahTJooe/+ToQMizlowPxl20bT98N+VYrGF7ae83uKOQZ/1llnx9nAoCbqa1Gm8V6JAMhzFEBDK+/8KaGneTTYWV6es0oexcyGbsUf9YQbzGoVIhp7fEP/t078YRg4P8gOcByas9OmbNbw93PDQwqJZRGAyRwav166Yjito+P/1j09QfeyQ0dwscKaMu2LIXFPWjE1+UzZwPCuq2jJxPXfNO9K/5JxKP1JS/JMhBvXjZOOCIqY4c9gbqF6nWEiSRX83QgJWcG1/pcJx1WlFEI6SkeTwghYW9leCnhHEprZY17zeYiDvL8p58kJgfS3g2JhpCQOpoy59VrZMaeBk+O5eo2ZofJjYK5Zu7UIy/1oRWNRtAD+s+qvvwkDvhWl1acnbe5O/lkPI8W5E8QudPJfez6UHE6Hu+nZui/AMN3Nth9ZUGHrXiOG66ei7PO6WNls="

python:
    - "3.5"
    - "3.6"
    - "3.7"

install: pip install tox-travis

script: tox

build: python setup.py sdist

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: kutsurak
  password:
    # test.pypi
    secure: "fvAsJqAsPMDNGYYCkND0122loTqOi7GMRd4gIe5IfkuYe4w8EqXcgdWs+sbIc/Jnl7D2CUpnSRNJakIEZ/mZsXiH2DqPAI5iwlXPW/hoOWDoJslplArH59xM80oha2Cw7dLFt/PHbIgGSx8DzONiOPoivAClPqDdqgfdGn2XQTj6cw6GXvinoh2hXD/1oUDhmlx9mqqN8lVKAMxAltKnd8F0edwAm3XZZ6Mi1zmUXgPjbZb/MiKaYIN0RKAkTjydJwP5yDCiKxfl/cDa4X4BO73a29PvkrkbXiQsISdBu6yOrZQ7D2YZ1407KHsoEIKP2JhapndEaOJBUEt+GeVPb64XjGjaY27tw/STi3aBgrk6v64oHeXJjR2v1P0RkGGBge9wQXJWEwlUgS6GJvm9DmZh88FVklL+rfbX0odeMwZyYhqJGV7tPHvCMlBJ1bZIp6mcTELtD0h2i5LSYHnp/xeCRQapS7JQ+goaeBED09CX4/6eHsXnq5gB3QyUehu8yeRoFOrKqlPznulexo0nrRZsn5cUnFOi1p+7NtmGpkVtCXNYOhsjKqL5nypC3PfE/GQo01fFt+9foVbKasSiRLoyNXADWvG+Bmbees328yq9rmRWaRSh5gVCKNGWY+qQYDYfuLjq6ei0g55nZkFvpV/tfIJGsa5aJ8M7WAm3dCM="
  on:
    tags: true


notifications:
  email:
    on_success: change
    on_failure: change
